run:
  skip-dirs:
    - .tmp

linters:
  fast: true
  enable:
    - golint
    - govet
    - gosimple
    - goconst
    - goimports
    - staticcheck
  disable:
    - errcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst

    # False positives on CGO generated code
    - linters:
        - staticcheck
      text: "SA4000:"

    - path: listen(_no)?_reuseport\.go
      linters:
        - typecheck
      text: "declar"

    - linters:
        - typecheck
      text: "could not import C"
