language: go
go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip
env:
  - VIPS_VERSION=8.4.6
  - VIPS_VERSION=8.5.8
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential libxml2-dev libfftw3-dev libmagickwand-dev libopenexr-dev liborc-0.4-0 gobject-introspection libgsf-1-dev libglib2.0-dev liborc-0.4-dev
  - wget https://github.com/jcupitt/libvips/releases/download/v$VIPS_VERSION/vips-$VIPS_VERSION.tar.gz
  - tar -xzvf vips-$VIPS_VERSION.tar.gz
  - pushd vips-$VIPS_VERSION && ./configure --prefix=/usr && make && sudo make install && popd
script:
  - CGO_LDFLAGS_ALLOW="-s|-w" go build
